title: Kai (James) Zhang
position: Data Scientist/Engineer
affiliation: GIBDL, SRIBD
email: kaizhang@sribd.cn
keywords: Statistics, Data Science, Basketball
google_scholar: https://scholar.google.com/
github_link: https://github.com/yaoyao-liu/minimal-light
linkedin: https://www.linkedin.com/
avatar: ./assets/img/kai.jpg
google_analytics: UA-111540567-4
favicon: ./assets/img/kai.png
favicon_dark: ./assets/img/favicon-dark.png
description: This Kai (James) Zhang's personal webesite.
canonical: https://minimal-light.yyliu.net/
remote_theme: yaoyao-liu/minimal-light
